ProjectsCore/cart/urls.py
from django.urls import path
from cart import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

ProjectsCore/core/urls.py
from django.contrib import admin
from django.urls import path,include
from core.admin import admin_site

# Для медеа файлов
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin_site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('product', include('goods.urls', namespace='goods')),
    path('', include('main.urls', namespace='main')),
]


# Для медеа файлов
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

ProjectsCore/goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='catalog'),
    path('<slug:category_slug>/', views.catalog, name='catalog_category'),
    path('<int:id>/<slug:slug>/', views.product, name='product'),
]

ProjectsCore/main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

ProjectsCore/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>{{title}}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block stylesheet %}{% endblock  %}
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

  

    <link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.css" %}">
    
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">

 
    

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">

    
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static "css/icomoon.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>
  <body class="goto-here">
		<div class="py-1 bg-primary">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
	    		<div class="col-lg-12 d-block">
		    		<div class="row d-flex">
		    			<div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <a href="tel://{{content.phoneWork}}"><span class="text" itemprop="telephone" >{{content.phoneWork}}</a></span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <a href="mailto:{{content.emailWork}}"><span class="text">{{content.emailWork}}</a></span>
					    </div>
					    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
						    <span class="text">{{content.nameSite}}</span>
					    </div>
              
				    </div>
			    </div>
		    </div>
		  </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url "main:index" %}">{{content.nameSite}}</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Меню
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'main:index' %}" class="nav-link">Главная</a></li>
                <li class="nav-item"><a href="{% url 'goods:catalog' %}" class="nav-link">Магази</a></li>
                <li class="nav-item"><a href="{% url 'main:about' %}" class="nav-link">О нас</a></li>
                <li class="nav-item"><a href="{% url 'main:contact' %}" class="nav-link">Контакты</a></li>

                <li class="nav-item cta cta-colored">
                  <a href="{% url "cart:cart_detail" %}" class="nav-link">
                    <span class="icon-shopping_cart"></span>
                      {% with total_items=cart|length %}
                      {% if total_items > 0 %}
                      {{ total_items }}
                      {% else %}
                      0
                      {% endif %}
                      {% endwith %}
                  </a>
                </li>

	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->

    {% block content %}

    {% endblock content %}


    <footer class="ftco-footer ftco-section">
        <div class="container">
            <div class="row">
                <div class="mouse">
                          <a href="#" class="mouse-icon">
                              <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
                          </a>
                      </div>
            </div>
          <div class="row mb-5">
            <div class="col-md">
              <div class="ftco-footer-widget mb-4">
                <h2 class="ftco-heading-2">{{content.nameSite}}</h2>
                <p>Мы готовим так что бы вы возращялись, Мы готовим так что бы вы возращялись</p>
                <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                  <li class="ftco-animate"><a href="{{content.ulrWhatsApp}}"><span class="icon-telegram"></span></a></li>
                  <li class="ftco-animate"><a href="{{content.ulrWhatsApp}}"><span class="icon-whatsapp"></span></a></li>
                  <li class="ftco-animate"><a href="{{content.phoneWork}}"><span class="icon-phone"></span></a></li>
                </ul>
              </div>
            </div>
            <div class="col-md">
              <div class="ftco-footer-widget mb-4 ml-md-5">
                <h2 class="ftco-heading-2">Меню</h2>
                <ul class="list-unstyled">
                  <li><a href="#" class="py-2 d-block">Магазин</a></li>
                  <li><a href="#" class="py-2 d-block">О нас</a></li>
                  <li><a href="#" class="py-2 d-block">Контакты</a></li>
                </ul>
              </div>
            </div>
            <div class="col-md-4">
               <div class="ftco-footer-widget mb-4">
                <h2 class="ftco-heading-2">Помощь</h2>
                <div class="d-flex">
                    <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                      <li><a href="#" class="py-2 d-block">Информация о доставке</a></li>
                      {% comment %} <li><a href="#" class="py-2 d-block">Условия</a></li> {% endcomment %}
                      <li><a href="#" class="py-2 d-block">Политика конфиденциальности</a></li>
                      <li><a href="#" class="py-2 d-block">FAQ</a></li>
                    </ul>
                    {% comment %} <ul class="list-unstyled">
                      <li><a href="#" class="py-2 d-block">FAQ</a></li>
                      <li><a href="#" class="py-2 d-block">Contact</a></li>
                    </ul> {% endcomment %}
                  </div>
              </div>
            </div>
            <div class="col-md">
              <div class="ftco-footer-widget mb-4">
                  <h2 class="ftco-heading-2">В случае возникновение вопросов</h2>
                  <div class="block-23 mb-3">
                    <ul>
                      <li><span class="icon icon-map-marker"></span><span class="text">{{content.adressShop}}</span></li>
                      <li><a href="#"><span class="icon icon-phone"></span><span class="text">{{content.phoneWork}}</span></a></li>
                      <li><a href="#"><span class="icon icon-envelope"></span><span class="text">{{content.emailWork}}</span></a></li>
                    </ul>
                  </div>
              </div>
            </div>
          </div>
            
        </div>
    </footer>
      
    
  
    <!-- loader -->
    {% comment %} <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div> {% endcomment %}

    {% block js %}
    {% endblock js %}
    
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/scrollax.min.js' %}"></script>

    <script src="{% static 'js/main.js' %}"></script>
      
    </body>
  </html>