ProjectsCore/cart/urls.py
from django.urls import path
from cart import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

ProjectsCore/core/urls.py
from django.contrib import admin
from django.urls import path,include
from core.admin import admin_site

# Для медеа файлов
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin_site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('product', include('goods.urls', namespace='goods')),
    path('', include('main.urls', namespace='main')),
]


# Для медеа файлов
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

ProjectsCore/orders/urls.py
from django.urls import path
from orders import views


app_name = 'orders'


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

ProjectsCore/orders/models.py
from django.db import models
from goods.models import Product
# Create your models here.

class Order(models.Model):

    PAY_CHOISE = [
        ('C', 'Наличные'),
        ('M', 'Карта')
    ]

    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Номер телефона')
    address_street = models.CharField(max_length=250, verbose_name='Адрес Город/Улица')
    address_house = models.CharField(max_length=250, blank=True, null=True, verbose_name='Адрес Квартира/Подъезд')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    update = models.DateField(auto_now=True, verbose_name='Дата обновления')
    payment = models.CharField(max_length=1, choices=PAY_CHOISE, verbose_name='Оплата')
    

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields = ['-created'])
        ]
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
    
    def __str__(self):
        return f'Order  {self.id}'
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE, verbose_name='Продукт')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')

    def __str__(self):
        return str(self.id)
    
    def get_cost(self):
        return self.price * self.quantity
    

ProjectsCore/orders/forms.py
import re
from django import forms
from orders.models import Order

class OrderCreateForm(forms.Form):
    # class Meta:
    #     model = Order
    #     fields = ['first_name', 'last_name', 'phone', 'address', 'payment']

    first_name = forms.CharField()
    last_name = forms.CharField()
    phone = forms.CharField()
    payment = forms.ChoiceField(
        choices = [
        ('C', 'Наличные'),
        ('M', 'Карта')
    ],
    )
    address_street = forms.CharField(required=False)
    address_house = forms.CharField(required=False)
   

    # def clean_phone_number(self):
    #     data = self.cleaned_data['phone_number']

    #     if not data.isdigit():
    #         raise forms.ValidationError('Номер телефона должен содержать только цифры')
        
    #     pattern = re.compile(r'^\d{10}$')
    #     if not pattern.match(data):
    #         raise forms.ValidationError('Не верный формат номера ')

ProjectsCore/orders/views.py
from django.shortcuts import render
from orders.models import Order, OrderItem
from orders.forms import OrderCreateForm
from cart.cart import Cart
from django.http import HttpResponse
from telebot.management.commands.runbot import send_telegram_message_to_all


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(data=request.POST)
        if form.is_valid():
            order = Order.objects.create(
                            first_name = form.cleaned_data['first_name'],
                            last_name = form.cleaned_data['last_name'],
                            phone = form.cleaned_data['phone'],
                            address_street = form.cleaned_data['address_street'],
                            address_house = form.cleaned_data['address_house'],
                            payment = form.cleaned_data['payment'],
                        )

            for item in cart:
                OrderItem.objects.create(order=order,
                                        product=item['product'],
                                        price=item['price'],
                                        quantity=item['quantity'])
            # очистить корзину
            cart.clear()

            # Отправка сообщения в Telegram-бота
            try:
                message = f"Новый заказ 💌\nИмя:   {order.first_name}\nФамилия:   {order.last_name}\nНомер телефона:   {order.phone}\nУлица/Дом:   {order.address_street}\nКвартира/Подъезд:   {order.address_house}\nОплата:   {order.payment}"
                send_telegram_message_to_all(message)
            except Exception as e:
                print(f"Произошла ошибка при отправке сообщения в Telegram: {e}")


            return render(request,
                            'orders/created.html',
                            {'order': order})
        else:
            return HttpResponse('Форма не валид ')
    else:
        form = OrderCreateForm()
    return render(request,
                    'orders/create.html',
                    {'cart': cart, 'form': form})

ProjectsCore/orders/templates/orders/checkout.html
    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-7 ftco-animate">
						<form action="#" class="billing-form">
							<h3 class="mb-4 billing-heading">Billing Details</h3>
	          	<div class="row align-items-end">
	          		<div class="col-md-6">
	                <div class="form-group">
	                	<label for="firstname">Firt Name</label>
	                  <input type="text" class="form-control" placeholder="">
	                </div>
	              </div>
	              <div class="col-md-6">
	                <div class="form-group">
	                	<label for="lastname">Last Name</label>
	                  <input type="text" class="form-control" placeholder="">
	                </div>
                </div>
                <div class="w-100"></div>
		            <div class="col-md-12">
		            	<div class="form-group">
		            		<label for="country">State / Country</label>
		            		<div class="select-wrap">
		                  <div class="icon"><span class="ion-ios-arrow-down"></span></div>
		                  <select name="" id="" class="form-control">
		                  	<option value="">France</option>
		                    <option value="">Italy</option>
		                    <option value="">Philippines</option>
		                    <option value="">South Korea</option>
		                    <option value="">Hongkong</option>
		                    <option value="">Japan</option>
		                  </select>
		                </div>
		            	</div>
		            </div>
		            <div class="w-100"></div>
		            <div class="col-md-6">
		            	<div class="form-group">
	                	<label for="streetaddress">Street Address</label>
	                  <input type="text" class="form-control" placeholder="House number and street name">
	                </div>
		            </div>
		            <div class="col-md-6">
		            	<div class="form-group">
	                  <input type="text" class="form-control" placeholder="Appartment, suite, unit etc: (optional)">
	                </div>
		            </div>
		            <div class="w-100"></div>
		            <div class="col-md-6">
		            	<div class="form-group">
	                	<label for="towncity">Town / City</label>
	                  <input type="text" class="form-control" placeholder="">
	                </div>
		            </div>
		            <div class="col-md-6">
		            	<div class="form-group">
		            		<label for="postcodezip">Postcode / ZIP *</label>
	                  <input type="text" class="form-control" placeholder="">
	                </div>
		            </div>
		            <div class="w-100"></div>
		            <div class="col-md-6">
	                <div class="form-group">
	                	<label for="phone">Phone</label>
	                  <input type="text" class="form-control" placeholder="">
	                </div>
	              </div>
	              <div class="col-md-6">
	                <div class="form-group">
	                	<label for="emailaddress">Email Address</label>
	                  <input type="text" class="form-control" placeholder="">
	                </div>
                </div>
                <div class="w-100"></div>
                <div class="col-md-12">
                	<div class="form-group mt-4">
										<div class="radio">
										  <label class="mr-3"><input type="radio" name="optradio"> Create an Account? </label>
										  <label><input type="radio" name="optradio"> Ship to different address</label>
										</div>
									</div>
                </div>
	            </div>
	          </form><!-- END -->
					</div>
					<div class="col-xl-5">
	          <div class="row mt-5 pt-3">
	          	<div class="col-md-12 d-flex mb-5">
	          		<div class="cart-detail cart-total p-3 p-md-4">
	          			<h3 class="billing-heading mb-4">Cart Total</h3>
	          			<p class="d-flex">
		    						<span>Subtotal</span>
		    						<span>$20.60</span>
		    					</p>
		    					<p class="d-flex">
		    						<span>Delivery</span>
		    						<span>$0.00</span>
		    					</p>
		    					<p class="d-flex">
		    						<span>Discount</span>
		    						<span>$3.00</span>
		    					</p>
		    					<hr>
		    					<p class="d-flex total-price">
		    						<span>Total</span>
		    						<span>$17.60</span>
		    					</p>
								</div>
	          	</div>
	          	<div class="col-md-12">
	          		<div class="cart-detail p-3 p-md-4">
	          			<h3 class="billing-heading mb-4">Payment Method</h3>
									<div class="form-group">
										<div class="col-md-12">
											<div class="radio">
											   <label><input type="radio" name="optradio" class="mr-2"> Direct Bank Tranfer</label>
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
											<div class="radio">
											   <label><input type="radio" name="optradio" class="mr-2"> Check Payment</label>
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
											<div class="radio">
											   <label><input type="radio" name="optradio" class="mr-2"> Paypal</label>
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
											<div class="checkbox">
											   <label><input type="checkbox" value="" class="mr-2"> I have read and accept the terms and conditions</label>
											</div>
										</div>
									</div>
									<p><a href="#"class="btn btn-primary py-3 px-4">Place an order</a></p>
								</div>
	          	</div>
	          </div>
          </div> <!-- .col-md-8 -->
        </div>
      </div>
    </section> <!-- .section -->

		<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Subcribe to our Newsletter</h2>
          	<span>Get e-mail updates about our latest shops and special offers</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
   

ProjectsCore/orders/templates/orders/create.html
{% extends "base.html" %}

{% load static %}


{% block content %}


<section class="ftco-section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xl-7 ftco-animate">


        <form action='{% url "orders:order_create" %}' class="billing-form" method='post' >
          {% csrf_token %}
          <h4 class="mb-4 billing-heading">Данные заказа</h4>
          <div class="row align-items-end">



            <div class="col-md-6">
              <div class="form-group">
                <label for="id_first_name">Имя*</label>
                <input id="id_first_name" type="text" class="form-control" placeholder="Имя" name='first_name'>
                    </div>
                    {% if form.first_name.errors %}
                        <p>{{form.first_name.errors}}</p>
                    {% endif %}
            </div>


            <div class="col-md-6">
              <div class="form-group">
                  <label for="id_last_name">Фамилия*</label>
                <input id="id_last_name" type="text" class="form-control" placeholder="Фамилия" name='last_name'>
                {% if form.last_name.errors %}
                  <p>{{form.last_name.errors}}</p>
                {% endif %}
              </div>
            </div>
          



          <div class="w-100"></div>
            <div class="col-md-6">
                <div class="form-group">
                <label for="id_address_street">Адрес Город/Улица</label>
              <input id="id_address_street" name='address_street' type="text" 
              class="form-control" placeholder="Анапа садовая 12">
            </div>
                  {% if form.address_street.errors %}
                  <p>{{form.address_street.errors}}</p>
                  {% endif %}
            </div>

            <div class="col-md-6">
                <div class="form-group">
                  <label for="id_address_house">Адрес Квартира/Подъезд</label>
                  <input id="id_address_house" name='address_house' type="text" class="form-control" 
                  placeholder="Квартира 12 подъезд 1">
            </div>
                  {% if form.address_house.errors %}
                  <p>{{form.address_house.errors}}</p>
                  {% endif %}
          </div>

          

        <div class="w-100"></div>
          <div class="col-md-12">
          <div class="form-group">
              <label for="id_phone">Номер телефона*</label>
            <input id="id_phone" name='phone' type="text" 
            class="form-control" placeholder="+79180000000"
            required>
          </div>
            {% if form.phone.errors %}
              <p>{{form.phone.errors}}</p>
            {% endif %}
        </div>




            <div class="col-md-12">
              <div class="cart-detail p-3 p-md-4">
                <h3 class="billing-heading mb-4">Способ оплаты</h3>
                
                <div class="form-group">
                  <div class="col-md-12">
                    <div class="radio">
                       <label for="id_payment"><input type="radio" name="payment" class="mr-2" id="id_payment" value="C">Наличными курьеру</label>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-12">
                    <div class="radio">
                       <label for="id_payment"><input type="radio" name="payment" class="mr-2" id="id_payment" value="M">Картой курьеру</label>
                    </div>
                    {% if form.payment_on_get.errors %}
											    <p>{{form.payment_on_get.errors}}</p>
											{% endif %}
                  </div>
                </div>

                <div class="form-group">
                  <div class="col-md-12">
                    <div class="checkbox">
                       <label><input type="checkbox" value="" class="mr-2">Я прочитал и принимаю условия</label>
                    </div>
                  </div>
                </div>
                <button class="btn btn-primary py-3 px-4" type="submit">Оставить заказ</button>
                {% comment %} <p><a href="#"class="btn btn-primary py-3 px-4">Оставить заказ</a></p> {% endcomment %}
              </div>
            </div>
            
            


          </div>
      </form><!-- END -->
</div>
  <div class="col-xl-5">
        <div class="row mt-5 pt-3">
          <div class="col-md-12 d-flex mb-5">
            <div class="cart-detail cart-total p-3 p-md-4">
              <h3 class="billing-heading mb-4">Корзина</h3>
              
              <p class="d-flex">
                <span>Доставка</span>
                <span>0.00 ₽</span>
              </p>
              
              <hr>
              <p class="d-flex total-price">
                <span>Итого</span>
                <span>{{ cart.get_total_price }} ₽</span>
              </p>
            </div>
          </div>
         
        </div>
      </div> <!-- .col-md-8 -->
    </div>
  </div>
</section> <!-- .section -->



{% endblock content %}

ProjectsCore/orders/templates/orders/created.html
{% extends "base.html" %}
{% comment %} thanks.png {% endcomment %}

{% load static %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center vh-85">
    <div class="text-center" >
        <h1 class="mt-4">Спасибо за заказ!</h1>
        <p class="mt-1">С вами свяжится наш менеджер в течении 5 минут для подтверждения заказа</p>
        <img src="{% static "images/thanks.png" %}" alt="Спасибо за заказ"  class="img-fluid w-50 mb-0 p-0">
    </div>
</div>

{% endblock content %}